# Generated by Django 6.0 on 2026-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='escrow_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
