# Generated by Django 6.0 on 2026-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('task_payment', 'Task Payment'), ('wallet_funding', 'Wallet Funding'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
