# Generated by Django 6.0 on 2026-03-22 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing_app', '0002_chatmessage_notification'),
        ('wallet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'New Application'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('task_completed', 'Task Completed'), ('message', 'New Message'), ('payment_proof', 'Payment Proof Uploaded'), ('payment_verified', 'Payment Verified'), ('escrow_funded', 'Escrow Funded'), ('payment_released', 'Payment Released')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/%Y/%m/%d/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='outsourcing_app.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPaymentEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('funded', 'Funded'), ('released', 'Released to Worker'), ('refunded', 'Refunded to Poster'), ('disputed', 'Under Dispute')], default='pending', max_length=20)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outsourcing_app.paymentproof')),
                ('poster_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_escrows', to='wallet_app.wallet')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='outsourcing_app.task')),
                ('worker_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_escrows', to='wallet_app.wallet')),
            ],
        ),
    ]
