# Generated by Django 6.0 on 2026-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing_app', '0004_application_completed_application_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowrelease',
            options={'ordering': ['-released_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by_poster',
            field=models.BooleanField(default=False, help_text='Has the task poster marked this task as complete?'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by_worker',
            field=models.BooleanField(default=False, help_text='Has the worker marked this task as complete?'),
        ),
        migrations.AddField(
            model_name='task',
            name='poster_completed_at',
            field=models.DateTimeField(blank=True, help_text='When did the poster mark completion?', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_completed_at',
            field=models.DateTimeField(blank=True, help_text='When did the worker mark completion?', null=True),
        ),
    ]
